### PR TITLE
Update cquthesis.dtx

### PR DESCRIPTION
**Pull request by EigenSolver**
add package for general math symbol `amssymb`

### CODE REVIEW

**Review by nanmu42 — CHANGES_REQUESTED** [review]
You need to change dtx checksum as well so that latex cquthesis.ins works properly.

**Comment by EigenSolver** [comment]
Thanks for your response.

Will do that after finishing my thesis defence😂.. (just a little busy these days)

And thank your again for the template....Without it I will never finish a 60- page thesis...👏

**Comment by nanmu42** [comment]
You are very welcome.

Thank you for your contribution.

> Will do that after finishing my thesis defence.. (just a little busy these days)

Wish you defence your thesis sucessfully, have fun.

**Comment by nanmu42** [comment]
CI looks good, thank you!

**Pull request merged**
